version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/auth-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_SERVICE_NAME=auth-service
      - JWT_SECRET=your_jwt_secret
      - REFRESH_TOKEN_SECRET=your_refresh_token_secret
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - jaeger
      - rabbitmq
    networks:
      - app-network

  book-service:
    build: ./services/book-service
    ports:
      - "6000:6000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/book-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_SERVICE_NAME=book-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - jaeger
      - rabbitmq
    networks:
      - app-network

  notification-service:
    build: ./services/notification-service
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/notification-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
      - OTEL_SERVICE_NAME=notification-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - jaeger
      - rabbitmq
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Web UI
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge