### Get all notifications
GET http://localhost:6001/api/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMxZTc4YWFhOWNmZDdhMDIwYzljMzUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzEzMzIwMzEsImV4cCI6MTczMTMzMzgzMSwiYXVkIjoiNjczMWU3OGFhYTljZmQ3YTAyMGM5YzM1IiwiaXNzIjoibWVocmV0dS5jb20ifQ.DqDlzMZQtDt7ghQ-X8wEbPNDnTOJRs-z0CyKzr4kbF0

### Get notifications with pagination
GET http://localhost:6001/api/notifications?page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5ZjVhNTc2YzkzYTgwODUxYmZiMGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA4MDY2MzQsImV4cCI6MTczMDgwODQzNCwiYXVkIjoiNjcyOWY1YTU3NmM5M2E4MDg1MWJmYjBhIiwiaXNzIjoibWVocmV0dS5jb20ifQ.V9lzpRczWnOYaF851_OUdfOqCktmC5xgGV2YTZdUj5Q

### Get notifications by category
GET http://localhost:6001/api/notifications/category/SCIENCE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMxZTc4YWFhOWNmZDdhMDIwYzljMzUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzEzMjk5OTIsImV4cCI6MTczMTMzMTc5MiwiYXVkIjoiNjczMWU3OGFhYTljZmQ3YTAyMGM5YzM1IiwiaXNzIjoibWVocmV0dS5jb20ifQ.LfGwAH0o_X2r6OR8kpuy-plXQCb-87xjgjyaFt-5gLM

### Get unread notifications count
GET http://localhost:6001/api/notifications/unread/count
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMxZTc4YWFhOWNmZDdhMDIwYzljMzUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzEzMjk5OTIsImV4cCI6MTczMTMzMTc5MiwiYXVkIjoiNjczMWU3OGFhYTljZmQ3YTAyMGM5YzM1IiwiaXNzIjoibWVocmV0dS5jb20ifQ.LfGwAH0o_X2r6OR8kpuy-plXQCb-87xjgjyaFt-5gLM

### Mark single notification as read
PUT http://localhost:6001/api/notifications/672a05f547957a2cd6472131/read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5ZjVhNTc2YzkzYTgwODUxYmZiMGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA4MDY2MzQsImV4cCI6MTczMDgwODQzNCwiYXVkIjoiNjcyOWY1YTU3NmM5M2E4MDg1MWJmYjBhIiwiaXNzIjoibWVocmV0dS5jb20ifQ.V9lzpRczWnOYaF851_OUdfOqCktmC5xgGV2YTZdUj5Q

### Mark all notifications as read
PUT http://localhost:6001/api/notifications/mark-all-read
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMxZTc4YWFhOWNmZDdhMDIwYzljMzUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzEzMjk5OTIsImV4cCI6MTczMTMzMTc5MiwiYXVkIjoiNjczMWU3OGFhYTljZmQ3YTAyMGM5YzM1IiwiaXNzIjoibWVocmV0dS5jb20ifQ.LfGwAH0o_X2r6OR8kpuy-plXQCb-87xjgjyaFt-5gLM
### Delet notification
DELETE http://localhost:6001/api/notifications/6731f229fc3daf98338ff56a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzMxZTc4YWFhOWNmZDdhMDIwYzljMzUiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzEzMjk5OTIsImV4cCI6MTczMTMzMTc5MiwiYXVkIjoiNjczMWU3OGFhYTljZmQ3YTAyMGM5YzM1IiwiaXNzIjoibWVocmV0dS5jb20ifQ.LfGwAH0o_X2r6OR8kpuy-plXQCb-87xjgjyaFt-5gLM
