###Verify Token Route
POST http://localhost:5000/auth/verify-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzJhMjIwNDkzYzAyZGY2MmI4MjcwMTYiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA4MTQ1NDYsImV4cCI6MTczMDgxNjM0NiwiYXVkIjoiNjcyYTIyMDQ5M2MwMmRmNjJiODI3MDE2IiwiaXNzIjoibWVocmV0dS5jb20ifQ.hWmSemm3M4dHtnkMFOJIL2dGn7qgrEO9gQDDPu5SUr0

###Root Route
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5ZjVhNTc2YzkzYTgwODUxYmZiMGEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA4MDQ4MjcsImV4cCI6MTczMDgwNTQyNywiYXVkIjoiNjcyOWY1YTU3NmM5M2E4MDg1MWJmYjBhIiwiaXNzIjoibWVocmV0dS5jb20ifQ.WIm8bpCxu_mjFrj61nosHJ2B55lsffSzO8d7vhOQKjo
###Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "abebe.abreham@gmail.com",
    "password": "1234"
    
}

###Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "abebe.abreham@gmail.com",
    "password": "1234",
    "name": "Abebe",
    "role": "admin"
}

###Refresh Token Route
POST http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA3MjUxMTUsImV4cCI6MTczMzMxNzExNSwiYXVkIjoiNjcyODgzNzY4YTA1Y2E1NmZhZjQ0OWYwIiwiaXNzIjoibWVocmV0dS5jb20ifQ.JRnO0UxpmZQyGT4_35eMArHjc9MU_sO4B2mtNwtK60I"
}

###Logout Route
DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA3MjQ0NjIsImV4cCI6MTczMzMxNjQ2MiwiYXVkIjoiNjcyODgzNzY4YTA1Y2E1NmZhZjQ0OWYwIiwiaXNzIjoibWVocmV0dS5jb20ifQ.k04HcOnTW6YKN7Ry3Ouy6SOBiIuqe2fS2j5oqq6qYJ8"
}