###Verify Token Route
POST http://localhost:5000/auth/verify-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YTA5Yzg1NTBlYjUxMGNjOWViZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA3ODM3NTQsImV4cCI6MTczMDc4NDM1NCwiYXVkIjoiNjcyOWEwOWM4NTUwZWI1MTBjYzllYmQyIiwiaXNzIjoibWVocmV0dS5jb20ifQ.UElN7uazPEEk4AeznNSLIEnfoCXCugyRQuBC1D0ItGQ

###Root Route
GET http://localhost:5000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzI5YTA5Yzg1NTBlYjUxMGNjOWViZDIiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzA3ODMwODQsImV4cCI6MTczMDc4MzY4NCwiYXVkIjoiNjcyOWEwOWM4NTUwZWI1MTBjYzllYmQyIiwiaXNzIjoibWVocmV0dS5jb20ifQ._GveNNpLYIo3pUjPqKt-GL0vQtGC4w-SmIMTAhNUBaA
###Login Route
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "vvssdrip.abreham@gmail.com",
    "password": "1234",
    "role": "admin"
    
}

###Register Route
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email": "abebe.abreham@gmail.com",
    "password": "1234",
    "role": "user"
}

###Refresh Token Route
POST http://localhost:5000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA3MjUxMTUsImV4cCI6MTczMzMxNzExNSwiYXVkIjoiNjcyODgzNzY4YTA1Y2E1NmZhZjQ0OWYwIiwiaXNzIjoibWVocmV0dS5jb20ifQ.JRnO0UxpmZQyGT4_35eMArHjc9MU_sO4B2mtNwtK60I"
}

###Logout Route
DELETE http://localhost:5000/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MzA3MjQ0NjIsImV4cCI6MTczMzMxNjQ2MiwiYXVkIjoiNjcyODgzNzY4YTA1Y2E1NmZhZjQ0OWYwIiwiaXNzIjoibWVocmV0dS5jb20ifQ.k04HcOnTW6YKN7Ry3Ouy6SOBiIuqe2fS2j5oqq6qYJ8"
}